qbt:
  host: qbit-standard.media.svc.cluster.local
  user:
  pass:

settings:
  force_auto_tmm_ignore_tags:
    - Upload
    - cross-seed
  force_auto_tmm: false
  tracker_error_tag: issue
  nohardlinks_tag: noHL
  share_limits_tag: ~share_limit
  ignoreTags_OnUpdate:
    - noHL
    - issue
    - cross-seed
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached
  share_limits_min_num_seeds_tag: MinSeedsNotMet
  share_limits_last_active_tag: LastActiveLimitNotReached
  cross_seed_tag: cross-seed
  cat_update_all: true
  cat_filter_completed: true
  share_limits_filter_completed: true
  tag_nohardlinks_filter_completed: true
  force_retag_all: false
directory:
  root_dir: /data/torrents/standard
  remote_dir: /data/torrents/standard
  recycle_bin: /data/torrents/standard.RecycleBin
  torrents_dir: /qbit-standard/qBittorrent/BT_backup
  orphaned_dir: /data/torrents/standard/orphaned_data
  cross_seed:

cat:
  movies: /data/movies
  series: /data/series
  books: /data/books
  audiobooks: /data/audiobooks
  music: /data/music
  sport: /data/sport

tracker: {{ .QBITMANAGE_TRACKERS | nindent 2 }}


nohardlinks:
  - movies:
      exclude_tags:
        - MaM
  - series:
      exclude_tags:
        - MaM

recyclebin:
  enabled: true
  empty_after_x_days: 3
  save_torrents: false
  split_by_category: false

orphaned:
  empty_after_x_days: 3
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - '**/*.!qB'
  - '**/*_unpackerred'
  - /data/temp/**
  - /data/BT_backup/**
  - /data/completed/**
  - /data/cross-seeds/**
  - /data/usedforseeding/**
  - /data/links/**
  - '**/*.torrent'

notifiarr:
  apikey: "{{ .NOTIFIARR_QBITMANAGE_API_KEY }}"
  instance:

webhooks:
  error: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  function:
    recheck: notifiarr
    cat_update: notifiarr
    tag_update: notifiarr
    rem_unregistered: notifiarr
    tag_tracker_error: notifiarr
    rem_orphaned: notifiarr
    tag_nohardlinks: notifiarr
    share_limits: notifiarr
    cleanup_dirs: notifiarr
