---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app iperf
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      iperf:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: networkstatic/iperf3
              tag: latest
            command: ["iperf3"]
            args:
              - "-c"
              - "${TRUENAS_IP}"
              - "-P"
              - "4" # Simulate 4 concurrent streams
              - "-t"
              - "300"
              - "-i"
              - "1"
              - "-w"
              - "1M"
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              fsGroup: 568
