---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app iperf
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      iperf:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: networkstatic/iperf3
              tag: latest
            command: ["iperf3"]
            args:
              - "-c"
              - "${TRUENAS_IP}"
              # For UDP testing
              - "-u"
              - "-b"
              - "10G" # Set UDP bandwidth to 10Gbps
              - "-l"
              - "8972" # UDP buffer size (slightly below MTU)
              - "-t"
              - "300" # Test duration
              - "-i"
              - "60" # Report interval
              # Optional: add parallel streams for UDP
              - "-P"
              - "4"
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              fsGroup: 568
