---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app iperf
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      iperf:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: networkstatic/iperf3
              tag: latest
            command: ["iperf3"]
            args:
              - "-c"
              - "${TRUENAS_IP}"
              - "-P"
              - "4" # Simulate 4 concurrent streams
              - "-t"
              - "300"
              - "-i"
              - "1"
              - "-w"
              - "1M"
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              fsGroup: 568
