apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:5lheMfcytA6xeLWqC/7eAVUDb9gBNOQ5xM3tX4tEyrJA/VYr,iv:oYXvS3F88KiYhiY2JgcWcGVL1rHwnzhDpdvv+hTumbo=,tag:qIbDQxdF3s3uMUCe0V83sA==,type:str]
    credentials.json: ENC[AES256_GCM,data:2f/rMM50Ajm4LNrimtIwxKjjRUR5n7OgqVs3YCdghJwjig9/aR2VMc1NHist7QjbZ22SjQnVuPlL0AYTyG3AIyQwGSUzpidVZm5A0j6o/whWgAQ/1kRWYHDHgSrj0UPrQF+FOIQbPbhp/KQw3raIMsqfi5n7q5XSIJRVogRIBYTFrpzMGskzSHPC2PFaREtG5yo7/pfsT8yoRHmO+r95I/QLT6WdZP2JxblyrQhumQ==,iv:wOekZs15xi9s++7mK7MMKScUc21TH7rFvJEjpzrHpPs=,tag:430Ae47xqmYs43LLLDehjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w9dv5enm6meku23cr82tfdgdmkqntrg0mnw5qyt7azyd59qvnc0q0xunp8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVTZWN2NvZ1p6YWpCUytx
            SmlMemZCNzVYd29yZDFsamVkQ3loVy9PR0hVCk03ckd4ZzNuUm9NVFNlalM4d0hZ
            aTdiUWhOZmUrUXFBUmhKSGcvNHBqUjAKLS0tIFNWM1paeGZzWm9qQXRXVDFEYm4y
            enFHaGlEQmxSTUlMU0ZIc3BpMHV3Uk0KRf1ex4J9rFaOR6j7rErJ9kbsSiRidtR7
            wnTS1ciG5tj63isDphuFAepmso8XvZj21E0nS949+8Rg0c/kyzMdSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-10T19:43:04Z"
    mac: ENC[AES256_GCM,data:5kUsXIjwC5v5qum9mPDCDEIqIZ4h7Jdg1GJipOc1fZa1LgOnbIoU0Z4lmgQbg/H8snpT8pQ2qr9qQK5TQk4DIveWs/KGnaUovCe4gl0q91MKlpcurS/qfRrmEXWWo0oSSrdQ3h8iwnQJ//8uLwkflsCg31tqNvrCLk7kCAIAABE=,iv:5pqK47jLCRD0LBJPPohLSma7++RyRvnzBWtCOA6moDM=,tag:kBvqbg+TxXwLPUgkhUso6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
