---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: kometa-configmap
    files:
      - ./configs/config.yaml
  - name: kometa-custom-configs
    files:
      - ./custom/best-of.yaml
      - ./custom/movies_collections.yaml
      - ./custom/series_collections.yaml
generatorOptions:
  disableNameSuffixHash: true
patches:
  - patch: |
      $patch: delete
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: openebs-zfs-1m
    target:
      kind: StorageClass
      name: openebs-zfs-1m
