---
cache:
  path: $PTS_CACHE_DIR/trakt_cache

excluded-libraries:
  - Barnfilmer
  - Barnserier
  - Animefilmer
  - Animeserier
  - Sport
  - Musik

config:
  dotenv_override: true

logging:
  append: false
  debug: false
  filename: plextraktsync.log

sync:
  plex_to_trakt:
    collection: true
    ratings: false
    watched_status: true
  trakt_to_plex:
    liked_lists: false
    ratings: false
    watched_status: true
    watchlist: false

watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true

xbmc-providers:
  movies: tmdb
  shows: tvdb
