---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: recyclarr-secret
    template:
      engineVersion: v2
      data:
        RADARR_STANDARD_API_KEY: "{{ .RADARR_API_KEY }}"
        RADARR_KIDS_API_KEY: "{{ .RADARR_API_KEY }}"
        RADARR_ANIME_API_KEY: "{{ .RADARR_API_KEY }}"
        SONARR_STANDARD_API_KEY: "{{ .SONARR_API_KEY }}"
        SONARR_KIDS_API_KEY: "{{ .SONARR_API_KEY }}"
        SONARR_ANIME_API_KEY: "{{ .SONARR_API_KEY }}"
        SONARR_SPORT_API_KEY: "{{ .SONARR_API_KEY }}"
  dataFrom:
    - extract:
        key: radarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "RADARR_$1"

    - extract:
        key: sonarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "SONARR_$1"
