---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: readarr-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: readarr-secret
    template:
      engineVersion: v2
      data:
        READARR__API_KEY: "{{ .READARR_API_KEY }}"
  dataFrom:
    - extract:
        key: readarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "READARR_$1"
