kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-zfs
  annotations:
    volume.beta.kubernetes.io/storage-class: "openebs-zfs"
spec:
  storageClassName: openebs-zfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
