apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Yrh+DgOLvw4sooU=,iv:gpRZt//Cw7ishBL6pWaKY3Eqw1Rit6bGNoalpcJL7JY=,tag:KebIyUQYTXTKbdbQGmxr9g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:IpmsO6ky1SXwBhf7rD+guoDU8jXH,iv:4trC7nNtEG/Ha9YVV5WnwVIg6RGBTD6t6Mevu4cRxzA=,tag:abHNuZ1dAg68BAX6j56fEg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xWt3mZ3A9NWFZEJ/+eJCK4zGendiQxT00R6t5vIY9YOAH+Wa,iv:T3hF6TcXyMC2I1qQM4u7wzXFJxv6inj5tb/j0ew4Fqc=,tag:x+csVOE7aFrfFwWMp2esBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w9dv5enm6meku23cr82tfdgdmkqntrg0mnw5qyt7azyd59qvnc0q0xunp8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaHR2SWUwbGdYaWppQ2lD
            M0RVc25venZ1dVFsYmVxRk9KVU13Yk1aR2hzClRKNTlnUlJ1QlNUVkNVTmhVTHhF
            aWlxdk45aC9odTRPSEpOcVRyQ3EyY2MKLS0tIDZHSTM2L21NRWNESkFvYzFLNEx3
            QmRJaGRJQlRhVjQxVFUwbkNPSEszancKkIPX5CbnVEMWCsOFm53OKEq9v7sv0jcv
            MlT9D/vQlW37cq+K2vuWU9YoUgwjMEilblHOz/+pYx73sXn16lQM2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-10T20:33:15Z"
    mac: ENC[AES256_GCM,data:CsU0nnnwJuNjMzhFyHl43lIE5nDy2zHZ7r5itHyvE6pTU5VMXS8Dj9tiKaO6ojGVRMNhroQ3FpxYe+NQa1QvnsWg94wLp9461o8QnOuEGaOGW7igiAjHZJhTxEbRaWS3B905yotS2VAT2cor9iN850fGn8yyGINjVTmzS8AYiX4=,iv:Tg4bVmhi6Wo2ahePdYmP7lJyqAKyJwLPjCbnl2mL2d4=,tag:s3ohnELO7TGByb9Q5iwEFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
