apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:LwhrJofR6O3LtRo=,iv:6iOHksd3JgpVdz/jy6ro/bvoxHB1HVj3gZ7bx0AatqY=,tag:IE40egFvO6rL4fnoN9B5wA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Zlcn5dfvlz24O5A7plDpZP7NTYuc,iv:R22Lz9sFMBKsuamIeMAdunCoLU8cet10VRKIAinBXsY=,tag:XQep6TbsUTa8Tb6iCyaLGA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:BDrvj2AFzUS/cBqXWTfcdwk23p0GQXaWkvOGEMY1jIvs1n6s,iv:EmAqeAkNzqq9879tq8v5bM2gGZmShRnS6GFwoHpMWMY=,tag:fizmisSRYY3H1F0buV94Bg==,type:str]
    SECRET_R2_HOST: ENC[AES256_GCM,data:K/6ayA6M2oSEH1ghwTg72U9t4ZvABC2YKmyV5gfG2u1uWxBcD65TfCsqPjrWYdhkXFf2js/E08KHTI53CWJ1UDc=,iv:V9McfrF40gyupqAAf14FlKvQKOdaYMmccgkk3v7VuI0=,tag:94+6dAo2xoEQJK/b+spODA==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:FuEH4SwKLtm+OxSxbpdEQfwKXv5O57Y0zVPIvQ==,iv:OA7p1MtBCkuB2aRRgMNxNuS/PvyHr499amsCsOuj6ts=,tag:Mje4JcWWjzuAiKwnW15DXA==,type:str]
    BW_CLIENTID: ENC[AES256_GCM,data:0Cm7JWnz5zczlX2fghHjkdeYAYSKkvsQe/gDxtjpMozJLcAw1BelxXk=,iv:bbRR4wvcE10u767yS3vl9bVHUnNAq+GLSpV3BaNXll8=,tag:awlQs70AGqsO7ZPKbnv3YA==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:R1E23jEMZKisPQMCKvPgI12uWQiPUoQCT+AhNAsd,iv:RMwKUQ7w6LDycF+dJKI55WRvCANYAyvcrRv/MTU8AeU=,tag:FQY3/6X3i6pO3U5YScp/vw==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:68mcD4iSvtJINoLBaX8M0g13U6ygjdLr,iv:GOzYwJx1Z8I+HD10228Zop65TrQufpXBfXWyO4ljB2c=,tag:3Aar7G0C8mJSvSfNzIU5pQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w9dv5enm6meku23cr82tfdgdmkqntrg0mnw5qyt7azyd59qvnc0q0xunp8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UVIzeXZjM2h3ODF3YkhI
            QldneHE0bGNlUmovdXh5QVRtY1dZd0JWY0ZFCmluRXc0T0thZUNVQ2x4aCtESXJx
            ODA3MTlPOS9FUmlaNTlzRzZhaW15U2sKLS0tIFpMb2NubmlabldPdGE4Z1ZpMkk1
            eFJYWC9jaEovbjA2QTZhMDFDRWwrUEkKCzX3fNAw5JU1BRrAI4hFlGKtVUUmYYfq
            EwLrEpupk5SS3eLE6hrUnW2soWny4sHoN/1g1P/hFG9wW2yfxrzdsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T07:46:51Z"
    mac: ENC[AES256_GCM,data:eDzVVu7Ikgk8+9vtEjZv3Aq99Px+GaEnBcblH4P/Gfa8vtsZUNgQe33EbAOErxycrU0MNIzfy8Iru8XjsDY46GKmAx2775bgqlSPwkHL+Kl8f1fvbIkNc/lKyKZriFiP19stcpDbj5qqQiAeKmqgvoZMVshOZ4EPPV9P+VgjGGI=,iv:7SybN0NMcF/w7J3ITV53OSDbigrDatlAIag+ilSn+uQ=,tag:ZaEnleG741jzRSh07uK2wg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
