apiVersion: v1
kind: Pod
metadata:
  name: intel-gpu-top
spec:
  containers:
    - name: intel-gpu-top
      image: solipsist01/intel-gpu-top
      command: ["intel_gpu_top"]
      volumeMounts:
        - mountPath: /dev/dri
          name: dri
  volumes:
    - name: dri
      hostPath:
        path: /dev/dri
        type: Directory
