---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sports-organizer
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  values:
    controllers:
      main:
        type: deployment
        containers:
          app:
            image:
              repository: ghcr.io/s0len/sports-organizer
              tag: develop@sha256:cea9f37e9a07de86cf1c270afbd6b79e8b26360cebd300c9b9bb79dc12c986db
              pullPolicy: Always
            env:
              SRC_DIR: /data/torrents/sport
              DEST_DIR: /data/media/sport
              PROCESS_INTERVAL: 60
              PUSHOVER_NOTIFICATION: true
            envFrom:
              - secretRef:
                  name: sports-organizer-secret
            securityContext:
              privileged: false
        annotations:
          rollme: "$(date +%s)"

    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        runAsNonRoot: true
        fsGroup: 568

    persistence:
      data:
        type: nfs
        server: "${TRUENAS_IP}"
        path: /mnt/rust/data
        globalMounts:
          - path: /data
            readOnly: false

      tmp:
        type: emptyDir
        medium: Memory
