---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app audiobookshelf
  namespace: &namespace media
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/guarded
  path: ./kubernetes/apps/media/audiobookshelf/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  prune: false
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 500Mi
      GATUS_PATH: /ping
      GATUS_SUBDOMAIN: audiobookshelf
