quality_profiles:
  - name: WEB-1080p
    reset_unmatched_scores:
      enabled: true
    qualities:
      - name: WEB 1080p
        qualities:
          - WEBDL-1080p
          - WEBRip-1080p
      - name: Bluray-1080p
      - name: HDTV-1080p
      - name: WEB 720p
        qualities:
          - WEBRip-720p
          - WEBDL-720p
      - name: HDTV-720p

  - name: WEB-2160p
    reset_unmatched_scores:
      enabled: true
    qualities:
      - name: WEB 2160p
        qualities:
          - WEBDL-2160p
          - WEBRip-2160p
      - name: Bluray-1080p Remux
      - name: Bluray-1080p
      - name: WEB 1080p
        qualities:
          - WEBDL-1080p
          - WEBRip-1080p
      - name: HDTV-1080p
      - name: WEB 720p
        qualities:
          - WEBRip-720p
          - WEBDL-720p
      - name: HDTV-720p
