quality_profiles:
  - name: Swedish
    reset_unmatched_scores:
      enabled: true
      except:
        - Not Swedish
    qualities:
      - name: WEB 1080p
        qualities:
          - WEBDL-1080p
          - WEBRip-1080p
      - name: Bluray-1080p
      - name: HDTV-1080p
      - name: WEB 720p
        qualities:
          - WEBRip-720p
          - WEBDL-720p
      - name: HDTV-720p
