---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
spec:
  refreshInterval: 15
  provider:
    webhook:
      url: "http://bws-cache.https://vault.bitwarden.eu/#/sm/key/{{ .remoteRef.key }}"
      headers:
        Authorization: "Bearer {{ print .serviceaccount.token }}"
      result:
        jsonPath: "$.value"
      secrets:
      - name: serviceaccount
        secretRef:
          name: bitwarden-access-token
          key: token
          namespace: external-secrets
