apiVersion: v1
kind: Secret
metadata:
    name: bws-secret
    labels:
        external-secrets.io/type: webhook
stringData:
    token: 0.5fb40c07-2a8d-48ce-ad25-b1e800749cce.1UR4kHkkmYJmiZI3bidLpEHXHACZQ6:4LTGst+/F95te2d85t13Ig==
    ORG_ID: 1abb9875-ff90-45ac-8681-b1e600d0f1db
