---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  # TODO: Uncomment once pushover is setup
  # - ../../../../templates/gatus/external
configMapGenerator:
  - name: authelia-configmap
    files:
      - configuration.yaml=./config/configuration.yaml
generatorOptions:
  disableNameSuffixHash: true
