---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-ddns
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m
  values:
    controllers:
      new-plex-dubs:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/hotio/cloudflareddns
              tag: latest@sha256:f87ce500681d5460d0001845776fc63a7a850c88404d54a4949dd3663923465d
            env:
              TZ: ${TIMEZONE}
              PUID: 568
              PGID: 568
              INTERVAL: 300
              DETECTION_MODE: dig-whoami.cloudflare
              CF_HOSTS: ${SECRET_DOMAIN}
              CF_ZONES: ${SECRET_DOMAIN}
              CF_RECORDTYPES: A
            envFrom:
              - secretRef:
                  name: cloudflare-ddns-secret
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 5m
                memory: 10Mi
              limits:
                memory: 1Gi

    persistence:
      config:
        type: emptyDir
