---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app fio
spec:
  interval: 30m
  chart:
    spec:
      chart: fio
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: fio
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      fio:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: xridge/fio
              tag: latest
            command: ["fio"]
            args:
              - "--name=nfs-video-playback"
              - "--filename=/data/test.fio"
              - "--direct=1"
              - "--rw=read"
              - "--bs=1M"
              - "--ioengine=libaio"
              - "--iodepth=8"
              - "--runtime=300"
              - "--time_based"
              - "--group_reporting"
              - "--numjobs=1"
              - "--size=10G"
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              fsGroup: 568
    persistence:
      data:
        type: nfs
        server: ${TRUENAS_IP}
        path: /mnt/rust/data/media
        globalMounts:
          - path: /data
            readOnly: false
