---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app fio
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      fio:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: xridge/fio
              tag: latest
            command: ["fio"]
            args:
              - "--name=nfs-video-playback"
              - "--filename=/data/test.fio"
              - "--direct=1"
              - "--rw=read"
              - "--bs=1M"
              - "--ioengine=libaio"
              - "--iodepth=8"
              - "--runtime=300"
              - "--time_based"
              - "--group_reporting"
              - "--numjobs=1"
              - "--size=10G"
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              fsGroup: 568
    persistence:
      data:
        type: nfs
        server: ${TRUENAS_IP}
        path: /mnt/rust/data/media
        globalMounts:
          - path: /data
            readOnly: false
