---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app hortusfox-web
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: dragonfly-cluster
    - name: external-secrets-stores
  path: ./kubernetes/apps/default/hortusfox-web/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  timeout: 15m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
      GATUS_SUBDOMAIN: hortusfox
