---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app unifi-controller
  namespace: flux-system
spec:
  targetNamespace: network
  dependsOn:
    - name: external-secrets-stores
  path: ./kubernetes/apps/network/unifi-controller/app
  prune: false # Enable later
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: unifi-controller
      VOLSYNC_CAPACITY: 2Gi
