apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-gpu-plugin
spec:
  rules:
    - name: intel.gpu
      labels:
        gpu.intel.com/i915: "true"
        gpu.intel.com/cards: "1"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["8086"]}
            class: {op: In, value: ["0300", "0380"]}
