---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hortusfox
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hortusfox-secret
    template:
      data:
        HORTUSFOX_USERNAME: "{{ .HORTUSFOX_USER }}"
        HORTUSFOX_PASSWORD: "{{ .HORTUSFOX_PASS }}"

        SMTP_PASS: "{{ .SMTP_PASS }}"
        SMTP_USER: "{{ .SMTP_USER }}"
        SMTP_HOST: smtp.gmail.com

        INIT_POSTGRES_DBNAME: hortusfox
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .HORTUSFOX_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .HORTUSFOX_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .CNPG_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: hortusfox
      rewrite:
        - regexp:
            source: "(.*)"
            target: "HORTUSFOX_$1"

    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "CNPG_$1"

    - extract:
        key: smtp
      rewrite:
        - regexp:
            source: "(.*)"
            target: "SMTP_$1"
