---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app hortusfox
spec:
  timeout: 15m
  interval: 30m
  chart:
    spec:
      chart: hortusfox
      version: 6.6.3
      sourceRef:
        kind: HelmRepository
        name: hortusfox
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
              repository: ghcr.io/danielbrendel/hortusfox-web
              tag: v4.0

    hortusfox:
      extraInitContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:16
          envFrom:
            - secretRef:
                name: hortusfox-secret

      extraEnv:
        - name: REDIS_HOST
          value: dragonfly.database.svc.cluster.local.
        - name: REDIS_HOST_PORT
          value: "6379"

      existingSecret:
        enabled: true
        secretName: hortusfox-secret
        usernameKey: hortusfox_USERNAME
        passwordKey: hortusfox_PASSWORD
        smtpUsernameKey: SMTP_USER
        smtpPasswordKey: SMTP_PASS
        smtpHostKey: SMTP_HOST

      host: cloud.${SECRET_DOMAIN}

      mail:
        enabled: true
        fromAddress: ${SECRET_USERNAME}
        domain: gmail.com
        smtp:
          host: smtp.gmail.com
          port: 465
          authtype: LOGIN
          secure: ssl

      configs:

    deploymentAnnotations:
      reloader.stakater.com/auto: "true"

    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true
      type: postgresql
      host: postgres16-rw.database.svc.cluster.local:5432
      database: *app
      existingSecret:
        enabled: true
        secretName: hortusfox-secret
        usernameKey: INIT_POSTGRES_USER
        passwordKey: INIT_POSTGRES_PASS

    ingress:
      enabled: true
      className: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      path: /
      pathType: Prefix

    persistence:
      enabled: true
      existingClaim: *app

    cronjob:
      enabled: true

    startupProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 10
      successThreshold: 1

    resources:
      requests:
        cpu: 50m
      limits:
        memory: 2Gi
