---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app hortusfox-web
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 3

  install:
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  uninstall:
    keepHistory: false

  values:
    controllers:
      hortusfox-web:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/danielbrendel/hortusfox-web
              tag: v4.4

            env:
              APP_ADMIN_EMAIL: HORTUSFOX_USERNAME
              APP_ADMIN_PASSWORD: HORTUSFOX_PASSWORD
              DB_HOST: postgres16-rw.database.svc.cluster.local
              DB_PORT: 5432
              DB_DATABASE: hortusfox
              DB_USERNAME: hortusfox
              DB_PASSWORD: hortusfox
              DB_CHARSET: "utf8mb4"

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes

            resources:
              requests:
                cpu: 100m
              limits:
                memory: 5Gi

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "plants.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http

    persistence:
      config:
        existingClaim: *app
