---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ./intel-gpu-exporter.yaml
  - ./intel-gpu-dashboard.yaml
